/** Ops Agent 的稳定名称、轮次与工具能力边界。 */

export const OPS_TOOL_WHITELIST = [
  "reader",
  "read_file",
  "read_image",
  "web_fetch",
  "write_file",
  "edit_file",
  "glob",
  "grep",
  "use_terminal",
  "terminal/*",
  "search_internet",
  "use_browser",
  "browser/*",
  "board/*",
  "skill",
  "use_skill",
  "search_skill",
  "install_skill",
  "create_skill",
  "todo/*",
  "agent_team",
  "agent_message",
  "agent_manage",
  "agent_send",
  "project",
  "project_agent",
  "project_manage",
  "project_send",
  "change_self",
  "get_goal",
  "create_goal",
  "update_goal",
  "submit_plan",
  "yield",
  "mcp",
] as const;

export const DEFAULT_OPS_AGENT_NAME = "ops";
export const DEFAULT_OPS_ROUND_LIMIT = 80;
