// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)

let nativeBinding = null
const loadErrors = []

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH)
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./terminal_engine.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./terminal_engine.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./terminal_engine.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    if (process.arch === 'x64') {
      try {
        return require('./terminal_engine.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./terminal_engine.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      try {
        return require('./terminal_engine.linux-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./terminal_engine.linux-arm64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

const {
  initEngine,
  setPersistPath,
  run,
  runBackground,
  write,
  stop,
  logs,
  list,
  remove,
  cleanupAgent,
  shutdown,
  setFilter,
  loadFilterFromFile,
  setSandbox,
  getSandboxPrompt,
  statusPanel,
  terminalCount,
} = nativeBinding

export {
  initEngine,
  setPersistPath,
  run,
  runBackground,
  write,
  stop,
  logs,
  list,
  remove,
  cleanupAgent,
  shutdown,
  setFilter,
  loadFilterFromFile,
  setSandbox,
  getSandboxPrompt,
  statusPanel,
  terminalCount,
}
