import React from "react";
import { render } from "ink-testing-library";
import { EventEmitter } from "node:events";
const { App } = await import("file:///Users/mac/Documents/vscodeProject/maou-sdk/cli/dist/app.js");
const cfg = (await import("file:///Users/mac/Documents/vscodeProject/maou-sdk/agent/coding-agent/dist/cli-config.js")).default;
const fakeStdout = Object.assign(new EventEmitter(), { columns: 100, rows: 32, isTTY: true, write:()=>true });
const fakeStdin = Object.assign(new EventEmitter(), { isTTY: true, setEncoding:()=>{}, setRawMode:()=>fakeStdin, ref:()=>{}, unref:()=>{}, resume:()=>fakeStdin, pause:()=>fakeStdin, read:()=>null });
Object.defineProperty(process, "stdout", { value: fakeStdout, configurable: true });
Object.defineProperty(process, "stdin", { value: fakeStdin, configurable: true });
const { frames, stdin } = render(React.createElement(App, { config: cfg }), { stdout: fakeStdout, stdin: fakeStdin });
await new Promise(r=>setTimeout(r,200));
stdin.write("abc");
await new Promise(r=>setTimeout(r,150));
stdin.write("\x1b[<0;8;30M");
await new Promise(r=>setTimeout(r,150));
stdin.write("def");
await new Promise(r=>setTimeout(r,150));
const strip = s => s.replace(/\x1b\[[0-9;?]*[a-zA-Z~<]/g,"").replace(/\x1b[()][AB0-2]/g,"").replace(/\r/g,"");
const last = strip(frames[frames.length-1]||"");
const inputLine = (last.split("\n").find(l=>l.includes("❯"))||"").trim();
console.log("输入框行:", JSON.stringify(inputLine));
const leak = inputLine.includes("[<0;") || inputLine.includes("8;30M");
console.log("SGR泄漏进文本:", leak);
process.exit(0);
