#!/usr/bin/env bash
# Install the `maou` CLI launcher so users can run it without manual PATH setup.
#
# Strategy (most reliable first):
#   1. Write canonical launcher under ~/.maou/bin/maou
#   2. Symlink/copy into dirs already on PATH or commonly on PATH and writable:
#        - $(brew --prefix)/bin   (macOS Homebrew — almost always on PATH)
#        - ~/.local/bin           (XDG / many tools)
#        - ~/.cargo/bin           (Rust users)
#   3. Patch common shell rc files if still needed
#   4. Verify `maou` resolves; print clear recovery if not
#
# Usage (from install.sh / update):
#   bash scripts/install-cli-launcher.sh <repo_root> [cli_dist_js]
#
set -euo pipefail

log() { printf '%s\n' "$*" >&2; }

REPO_ROOT="${1:-}"
CLI_DIST="${2:-}"

if [[ -z "$REPO_ROOT" || ! -d "$REPO_ROOT" ]]; then
  log "error: install-cli-launcher.sh needs monorepo root"
  exit 1
fi

if [[ -z "$CLI_DIST" ]]; then
  CLI_DIST="$REPO_ROOT/cli/dist/index.js"
fi
if [[ ! -f "$CLI_DIST" ]]; then
  log "error: cli dist missing: $CLI_DIST"
  exit 1
fi

# Canonical absolute path (spaces-safe)
CLI_DIST="$(cd "$(dirname "$CLI_DIST")" && pwd)/$(basename "$CLI_DIST")"

MAOU_HOME="${MAOU_HOME:-$HOME/.maou}"
BIN_DIR="${MAOU_BIN_DIR:-$MAOU_HOME/bin}"
mkdir -p "$BIN_DIR" "$MAOU_HOME"

WRAP="$BIN_DIR/maou"
# Robust launcher: fixed CLI_DIST from this install; still overridable via MAOU_CLI_JS
cat > "$WRAP" <<EOF
#!/usr/bin/env bash
# Generated by maou-sdk scripts/install-cli-launcher.sh — do not edit by hand
set -euo pipefail
CLI_JS="\${MAOU_CLI_JS:-$CLI_DIST}"
if [[ ! -f "\$CLI_JS" ]]; then
  echo "maou: CLI entry not found: \$CLI_JS" >&2
  echo "  Re-run: cd <maou-sdk> && bash scripts/install.sh" >&2
  exit 127
fi
if ! command -v node >/dev/null 2>&1; then
  echo "maou: node not found (need Node >= 20 on PATH)" >&2
  exit 127
fi
exec node "\$CLI_JS" "\$@"
EOF
chmod +x "$WRAP"
log "[maou] launcher: $WRAP"

# --- Place maou where shells already look ---
install_link() {
  local dest_dir="$1"
  [[ -n "$dest_dir" && -d "$dest_dir" && -w "$dest_dir" ]] || return 1
  # Prefer symlink so updates to ~/.maou/bin/maou apply; fall back to copy
  if ln -sfn "$WRAP" "$dest_dir/maou" 2>/dev/null; then
    log "[maou] linked: $dest_dir/maou → $WRAP"
    return 0
  fi
  if cp -f "$WRAP" "$dest_dir/maou" 2>/dev/null; then
    chmod +x "$dest_dir/maou"
    log "[maou] copied: $dest_dir/maou"
    return 0
  fi
  return 1
}

# Collect candidate dirs: brew first (macOS default PATH), then XDG, cargo
CANDIDATES=()
if command -v brew >/dev/null 2>&1; then
  _bp="$(brew --prefix 2>/dev/null || true)"
  [[ -n "$_bp" ]] && CANDIDATES+=("$_bp/bin")
fi
CANDIDATES+=("$HOME/.local/bin")
CANDIDATES+=("${CARGO_HOME:-$HOME/.cargo}/bin")
# Extra Homebrew paths even if brew CLI missing
CANDIDATES+=("/opt/homebrew/bin" "/usr/local/bin")

LINKED=0
SEEN="|"
for d in "${CANDIDATES[@]}"; do
  [[ -z "$d" ]] && continue
  case "$SEEN" in
    *"|$d|"*) continue ;;
  esac
  SEEN="${SEEN}${d}|"
  if install_link "$d"; then
    LINKED=$((LINKED + 1))
  fi
done

# --- Patch shell rc files so new terminals always see ~/.maou/bin ---
# (Conda/login shells sometimes skip .zshrc; cover zprofile + bash profile too.)
PATH_LINE='export PATH="$HOME/.maou/bin:$HOME/.local/bin:$PATH"'
patch_rc() {
  local rc="$1"
  local dir
  dir="$(dirname "$rc")"
  mkdir -p "$dir" 2>/dev/null || true
  [[ -e "$rc" || -w "$dir" ]] || return 0
  if [[ -f "$rc" ]] && grep -qF '.maou/bin' "$rc" 2>/dev/null; then
    return 0
  fi
  {
    echo ""
    echo "# Maou CLI (added by install.sh — enables \`maou\` without manual PATH)"
    echo "$PATH_LINE"
  } >> "$rc" 2>/dev/null && log "[maou] PATH → $rc" || true
}

case "$(uname -s 2>/dev/null || echo unknown)" in
  Darwin|Linux)
    patch_rc "$HOME/.zprofile"
    patch_rc "$HOME/.zshrc"
    patch_rc "$HOME/.bash_profile"
    patch_rc "$HOME/.bashrc"
    patch_rc "$HOME/.profile"
    if [[ -d "$HOME/.config/fish" ]] || command -v fish >/dev/null 2>&1; then
      mkdir -p "$HOME/.config/fish"
      fish_rc="$HOME/.config/fish/config.fish"
      if [[ ! -f "$fish_rc" ]] || ! grep -qF '.maou/bin' "$fish_rc" 2>/dev/null; then
        {
          echo ""
          echo "# Maou CLI"
          echo 'set -gx PATH $HOME/.maou/bin $HOME/.local/bin $PATH'
        } >> "$fish_rc" 2>/dev/null && log "[maou] PATH → $fish_rc" || true
      fi
    fi
    ;;
esac

# Current session
export PATH="$BIN_DIR:$HOME/.local/bin:${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
if command -v brew >/dev/null 2>&1; then
  _bp="$(brew --prefix 2>/dev/null || true)"
  [[ -n "$_bp" ]] && export PATH="$_bp/bin:$PATH"
fi
hash -r 2>/dev/null || true

# Verify
if command -v maou >/dev/null 2>&1; then
  log "[maou] OK: \`maou\` is on PATH → $(command -v maou)"
  log "[maou]     try: maou doctor"
  exit 0
fi

# Soft success: files installed; user may need new terminal if nothing on PATH was writable
log "[maou] ⚠ installed launcher but \`maou\` not yet on THIS shell's PATH."
log "[maou]   Open a new terminal, or run once:"
log "[maou]     export PATH=\"\$HOME/.maou/bin:\$HOME/.local/bin:\$PATH\""
log "[maou]     hash -r && maou doctor"
if [[ "$LINKED" -eq 0 ]]; then
  log "[maou]   (no writable standard bin dir found; only $WRAP was installed)"
fi
exit 0
