$ErrorActionPreference = "Stop"

function Log([string]$msg) { Write-Host $msg }
function Die([string]$msg) {
  Write-Host "error: $msg" -ForegroundColor Red
  exit 1
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Die "Node.js not found. Install Node >= 20 from https://nodejs.org then re-run."
}
$nodeMajor = [int](node -p "process.versions.node.split('.')[0]")
if ($nodeMajor -lt 20) {
  Die "Node >= 20 required (found $(node -v))"
}
if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
  Die "npm not found (comes with Node)"
}
if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
  Die "pnpm required. Install: npm i -g pnpm"
}
if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
  Die "Rust required. Install: winget install Rustlang.Rustup (then restart terminal)"
}

$homeDir = if ($env:USERPROFILE) { $env:USERPROFILE } else { $env:HOME }
$maouHome = if ($env:MAOU_HOME) { $env:MAOU_HOME } else { Join-Path $homeDir ".maou" }
$binDir = if ($env:MAOU_BIN_DIR) { $env:MAOU_BIN_DIR } else { Join-Path $maouHome "bin" }
New-Item -ItemType Directory -Force -Path $binDir | Out-Null
New-Item -ItemType Directory -Force -Path $maouHome | Out-Null

$scriptDir = $PSScriptRoot
if (-not $scriptDir) {
  $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
}
$repoRoot = Split-Path -Parent $scriptDir

if (-not (Test-Path (Join-Path $repoRoot "pnpm-workspace.yaml")) -or -not (Test-Path (Join-Path $repoRoot "cli"))) {
  Die "Not a maou-sdk monorepo. Clone the full repo and run install.ps1 from it."
}

Log "[maou] monorepo: $repoRoot"
Log "[maou] building Core (fail-closed)..."

$buildNative = Join-Path $repoRoot "scripts\build-native.ps1"
if (Test-Path $buildNative) {
  $buildProcess = Start-Process -FilePath "powershell" -ArgumentList @("-ExecutionPolicy", "Bypass", "-File", $buildNative) -NoNewWindow -PassThru -Wait
  if ($buildProcess.ExitCode -ne 0) {
    Die "build-native.ps1 failed with exit code $($buildProcess.ExitCode)"
  }
} else {
  Push-Location $repoRoot
  try {
    pnpm install
    pnpm -r run build
  } catch {
    Die "pnpm build failed"
  } finally {
    Pop-Location
  }
}

$cliDist = Join-Path $repoRoot "cli\dist\index.js"
if (-not (Test-Path $cliDist)) {
  Die "cli\dist\index.js missing after build - Core incomplete"
}

$wrapCmd = Join-Path $binDir "maou.cmd"
New-Item -ItemType Directory -Force -Path $binDir | Out-Null
@"
@echo off
REM Generated by install.ps1 — launches maou CLI
node "$cliDist" %*
"@ | Set-Content -Encoding ASCII $wrapCmd
Log "[maou] wrapper: $wrapCmd"

# Also install to locations Windows often already has on PATH (zero manual PATH when possible)
$extraBins = [System.Collections.Generic.List[string]]::new()
$extraBins.Add((Join-Path $homeDir ".local\bin")) | Out-Null
$extraBins.Add((Join-Path $homeDir ".cargo\bin")) | Out-Null
# npm global prefix\bin is almost always on PATH after Node install
try {
  $npmPrefix = (npm config get prefix 2>$null)
  if ($npmPrefix -and (Test-Path $npmPrefix)) {
    $npmBin = Join-Path $npmPrefix "bin"
    if (-not (Test-Path $npmBin)) { $npmBin = $npmPrefix } # Windows npm often uses prefix itself
    $extraBins.Add($npmBin) | Out-Null
  }
} catch { }
# pnpm home (if set)
if ($env:PNPM_HOME) { $extraBins.Add($env:PNPM_HOME) | Out-Null }

foreach ($d in $extraBins) {
  try {
    New-Item -ItemType Directory -Force -Path $d | Out-Null
    Copy-Item $wrapCmd (Join-Path $d "maou.cmd") -Force
    Log "[maou] copied: $(Join-Path $d 'maou.cmd')"
  } catch {
    # ignore unwritable dirs
  }
}

$ensureDcg = Join-Path $repoRoot "scripts\ensure-dcg.mjs"
if (Test-Path $ensureDcg) {
  Log "[maou] ensuring dcg..."
  $dcgProcess = Start-Process -FilePath "node" -ArgumentList @($ensureDcg, "--user") -NoNewWindow -PassThru -Wait
  if ($dcgProcess.ExitCode -ne 0) {
    Log "[maou] WARNING: dcg failed - Terminal security degraded. Later: node scripts\ensure-dcg.mjs --user"
  }
}

$ensureRg = Join-Path $repoRoot "scripts\ensure-rg.mjs"
if (Test-Path $ensureRg) {
  Log "[maou] ensuring rg (ripgrep)..."
  $rgProcess = Start-Process -FilePath "node" -ArgumentList @($ensureRg, "--user") -NoNewWindow -PassThru -Wait
  if ($rgProcess.ExitCode -ne 0) {
    Log "[maou] WARNING: rg failed - grep falls back to Node.js. Later: node scripts\ensure-rg.mjs --user"
  }
}

# sqry: required for Coding Agent find_code
$ensureSqry = Join-Path $repoRoot "scripts\ensure-sqry.mjs"
if (Test-Path $ensureSqry) {
  Log "[maou] ensuring sqry (find_code)..."
  $sqryProcess = Start-Process -FilePath "node" -ArgumentList @($ensureSqry, "--user") -NoNewWindow -PassThru -Wait
  if ($sqryProcess.ExitCode -ne 0) {
    Log "[maou] ensure-sqry failed, try cargo install sqry-cli..."
    $cargo = Get-Command cargo -ErrorAction SilentlyContinue
    if ($cargo) {
      & cargo install sqry-cli
      if ($LASTEXITCODE -ne 0) {
        throw "sqry install failed — find_code unavailable. Manual: node scripts\ensure-sqry.mjs --user"
      }
      $cargoSqry = Join-Path $env:USERPROFILE ".cargo\bin\sqry.exe"
      if (Test-Path $cargoSqry) {
        Copy-Item $cargoSqry (Join-Path $binDir "sqry.exe") -Force
      }
    } else {
      throw "sqry install failed and no cargo. Manual: node scripts\ensure-sqry.mjs --user"
    }
  }
}

# Always ensure User PATH has ~/.maou/bin and ~/.local/bin (no manual GUI setup)
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (-not $userPath) { $userPath = "" }
$need = @($binDir, (Join-Path $homeDir ".local\bin"))
$changed = $false
foreach ($d in $need) {
  if ($userPath -notlike "*$d*") {
    $userPath = "$d;$userPath"
    $changed = $true
  }
}
if ($changed) {
  [Environment]::SetEnvironmentVariable("Path", $userPath, "User")
  # Notify Windows that User PATH changed (helps some shells/apps pick it up)
  try {
    Add-Type -Namespace Win32 -Name Native -MemberDefinition @"
[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
"@ -ErrorAction SilentlyContinue
    $HWND_BROADCAST = [IntPtr]0xffff
    $WM_SETTINGCHANGE = 0x1a
    $result = [UIntPtr]::Zero
    [void][Win32.Native]::SendMessageTimeout($HWND_BROADCAST, $WM_SETTINGCHANGE, [UIntPtr]::Zero, "Environment", 2, 5000, [ref]$result)
  } catch { }
  Log "[maou] Updated User PATH (new PowerShell/CMD windows pick this up automatically)"
}
# Current session: prepend so `maou` works immediately after install
$env:Path = "$binDir;$(Join-Path $homeDir '.local\bin');$env:Path"

Log ""
Log "Install finished. Default TUI is Ratatui."
if (Get-Command maou -ErrorAction SilentlyContinue) {
  Log "  maou is ready NOW: $((Get-Command maou).Source)"
  Log "  try: maou doctor"
} else {
  Log "  Open a NEW PowerShell window, then: maou doctor"
  Log "  (or this session: `$env:Path = `"$binDir;`$env:Path`")"
}
Log "  maou doctor     # Core / Terminal / Coding (sqry required)"
Log "  maou setup"
Log "  maou coding"
Log "Done."