# Maou installer (Windows PowerShell). Does NOT install Node.
# Default: Node/pnpm + prebuilt natives (no Rust / VS Build Tools required).
# Dev local build: $env:MAOU_BUILD_NATIVE=1; .\scripts\install.ps1
$ErrorActionPreference = "Stop"

function Log([string]$msg) { Write-Host $msg }
function Die([string]$msg) {
  Write-Host "error: $msg" -ForegroundColor Red
  exit 1
}

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Die "Node.js not found. Install Node >= 20 from https://nodejs.org then re-run."
}
$nodeMajor = [int](node -p "process.versions.node.split('.')[0]")
if ($nodeMajor -lt 20) {
  Die "Node >= 20 required (found $(node -v))"
}
if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
  Die "npm not found (comes with Node)"
}
if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
  Die "pnpm required. Install: npm i -g pnpm"
}

$homeDir = if ($env:USERPROFILE) { $env:USERPROFILE } else { $env:HOME }
$maouHome = if ($env:MAOU_HOME) { $env:MAOU_HOME } else { Join-Path $homeDir ".maou" }
$binDir = if ($env:MAOU_BIN_DIR) { $env:MAOU_BIN_DIR } else { Join-Path $maouHome "bin" }
New-Item -ItemType Directory -Force -Path $binDir | Out-Null
New-Item -ItemType Directory -Force -Path $maouHome | Out-Null

$scriptDir = $PSScriptRoot
if (-not $scriptDir) {
  $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
}
$repoRoot = Split-Path -Parent $scriptDir

if (-not (Test-Path (Join-Path $repoRoot "pnpm-workspace.yaml")) -or -not (Test-Path (Join-Path $repoRoot "cli"))) {
  Die "Not a maou-sdk monorepo. Clone the full repo and run install.ps1 from it."
}

Log "[maou] monorepo: $repoRoot"
Log "[maou] building Core (JS)..."

Push-Location $repoRoot
try {
  pnpm install
  if ($LASTEXITCODE -ne 0) { Die "pnpm install failed" }
  pnpm -r run build
  if ($LASTEXITCODE -ne 0) { Die "pnpm build failed" }
} finally {
  Pop-Location
}

$cliDist = Join-Path $repoRoot "cli\dist\index.js"
if (-not (Test-Path $cliDist)) {
  Die "cli\dist\index.js missing after build - Core incomplete"
}

# Prebuilt natives (no Rust required)
Log "[maou] ensuring prebuilt terminal-engine..."
$te = Start-Process -FilePath "node" -ArgumentList @((Join-Path $repoRoot "scripts\ensure-terminal-engine.mjs")) -NoNewWindow -PassThru -Wait
if ($te.ExitCode -ne 0) {
  Log "[maou] WARNING: terminal-engine ensure had issues"
}

Log "[maou] ensuring prebuilt maou-tui..."
$tui = Start-Process -FilePath "node" -ArgumentList @((Join-Path $repoRoot "scripts\ensure-maou-tui.mjs")) -NoNewWindow -PassThru -Wait
if ($tui.ExitCode -ne 0) {
  Log "[maou] WARNING: maou-tui ensure had issues"
}

# Optional full local native build for developers
if ($env:MAOU_BUILD_NATIVE -eq "1" -or $env:MAOU_BUILD_NATIVE -eq "true") {
  if (Get-Command cargo -ErrorAction SilentlyContinue) {
    Log "[maou] MAOU_BUILD_NATIVE=1 -> build-native.ps1..."
    $bn = Join-Path $repoRoot "scripts\build-native.ps1"
    if (Test-Path $bn) {
      $bp = Start-Process -FilePath "powershell" -ArgumentList @("-ExecutionPolicy", "Bypass", "-File", $bn) -NoNewWindow -PassThru -Wait
      if ($bp.ExitCode -ne 0) {
        Log "[maou] WARNING: build-native failed"
      }
    }
  } else {
    Log "[maou] MAOU_BUILD_NATIVE=1 but cargo not found; skip local build"
  }
}

$wrapCmd = Join-Path $binDir "maou.cmd"
New-Item -ItemType Directory -Force -Path $binDir | Out-Null
@"
@echo off
REM Generated by install.ps1 — launches maou CLI
node "$cliDist" %*
"@ | Set-Content -Encoding ASCII $wrapCmd
Log "[maou] wrapper: $wrapCmd"

$extraBins = [System.Collections.Generic.List[string]]::new()
$extraBins.Add((Join-Path $homeDir ".local\bin")) | Out-Null
$extraBins.Add((Join-Path $homeDir ".cargo\bin")) | Out-Null
try {
  $npmPrefix = (npm config get prefix 2>$null)
  if ($npmPrefix -and (Test-Path $npmPrefix)) {
    $npmBin = Join-Path $npmPrefix "bin"
    if (-not (Test-Path $npmBin)) { $npmBin = $npmPrefix }
    $extraBins.Add($npmBin) | Out-Null
  }
} catch { }
if ($env:PNPM_HOME) { $extraBins.Add($env:PNPM_HOME) | Out-Null }

foreach ($d in $extraBins) {
  try {
    New-Item -ItemType Directory -Force -Path $d | Out-Null
    Copy-Item $wrapCmd (Join-Path $d "maou.cmd") -Force
    Log "[maou] copied: $(Join-Path $d 'maou.cmd')"
  } catch { }
}

$ensureDcg = Join-Path $repoRoot "scripts\ensure-dcg.mjs"
if (Test-Path $ensureDcg) {
  Log "[maou] ensuring dcg..."
  $dcgProcess = Start-Process -FilePath "node" -ArgumentList @($ensureDcg, "--user") -NoNewWindow -PassThru -Wait
  if ($dcgProcess.ExitCode -ne 0) {
    Log "[maou] WARNING: dcg failed - Terminal security degraded."
  }
}

$ensureRg = Join-Path $repoRoot "scripts\ensure-rg.mjs"
if (Test-Path $ensureRg) {
  Log "[maou] ensuring rg (ripgrep)..."
  $rgProcess = Start-Process -FilePath "node" -ArgumentList @($ensureRg, "--user") -NoNewWindow -PassThru -Wait
  if ($rgProcess.ExitCode -ne 0) {
    Log "[maou] WARNING: rg failed - grep falls back to Node.js."
  }
}

$ensureSqry = Join-Path $repoRoot "scripts\ensure-sqry.mjs"
if (Test-Path $ensureSqry) {
  Log "[maou] ensuring sqry (find_code)..."
  $sqryProcess = Start-Process -FilePath "node" -ArgumentList @($ensureSqry, "--user") -NoNewWindow -PassThru -Wait
  if ($sqryProcess.ExitCode -ne 0) {
    Log "[maou] ensure-sqry failed, try cargo install sqry-cli if cargo exists..."
    $cargo = Get-Command cargo -ErrorAction SilentlyContinue
    if ($cargo) {
      & cargo install sqry-cli
      if ($LASTEXITCODE -eq 0) {
        $cargoSqry = Join-Path $env:USERPROFILE ".cargo\bin\sqry.exe"
        if (Test-Path $cargoSqry) {
          Copy-Item $cargoSqry (Join-Path $binDir "sqry.exe") -Force
        }
      } else {
        Log "[maou] WARNING: sqry install failed"
      }
    } else {
      Log "[maou] WARNING: sqry unavailable (no prebuild/cargo)"
    }
  }
}

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (-not $userPath) { $userPath = "" }
$need = @($binDir, (Join-Path $homeDir ".local\bin"))
$changed = $false
foreach ($d in $need) {
  if ($userPath -notlike "*$d*") {
    $userPath = "$d;$userPath"
    $changed = $true
  }
}
if ($changed) {
  [Environment]::SetEnvironmentVariable("Path", $userPath, "User")
  try {
    Add-Type -Namespace Win32 -Name Native -MemberDefinition @"
[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)]
public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
"@ -ErrorAction SilentlyContinue
    $HWND_BROADCAST = [IntPtr]0xffff
    $WM_SETTINGCHANGE = 0x1a
    $result = [UIntPtr]::Zero
    [void][Win32.Native]::SendMessageTimeout($HWND_BROADCAST, $WM_SETTINGCHANGE, [UIntPtr]::Zero, "Environment", 2, 5000, [ref]$result)
  } catch { }
  Log "[maou] Updated User PATH"
}
$env:Path = "$binDir;$(Join-Path $homeDir '.local\bin');$env:Path"

Log ""
Log "Install finished."
if (Get-Command maou -ErrorAction SilentlyContinue) {
  Log "  maou is ready: $((Get-Command maou).Source)"
} else {
  Log "  Open a NEW PowerShell, then: maou doctor"
}
Log "  maou doctor / maou setup / maou coding"
Log ""
Log "Natives: downloaded from GitHub Release 'native-prebuilds' (no Rust required)."
Log "Dev local build: `$env:MAOU_BUILD_NATIVE=1; .\scripts\install.ps1"
Log "See docs/NATIVE_PREBUILD.md"
Log "Done."
