/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 扁平帧：row-major，长度 = rows * cols */
export interface FlatFrame {
  cols: number
  rows: number
  /** 每格字符；continuation 用空串 */
  ch: Array<string>
  /** 每格 SGR 前缀（可为空） */
  sgr: Array<string>
  /** 显示宽：1 正常，0 continuation，2+ 全角首格 */
  w: Array<number>
}
export interface PaintResult {
  /** 本帧每行编码后的字符串（供 JS 缓存 prevEncodedLines） */
  lines: Array<string>
  /** 可直接 write 的 ANSI（含光标定位）；无变化时为空 */
  out: string
  dirty: number
  /** true = 走了 native 路径 */
  native: boolean
}
/** 编码整帧并做行 diff，返回 stdout 用 ANSI。 */
export declare function paintDiff(frame: FlatFrame, themeBgSgr: string, prevLines: Array<string> | undefined | null, forceAll: boolean): PaintResult
/** 探测 native 是否可用 */
export declare function rasterVersion(): string
